name: CI

on:
  push:
  pull_request:

jobs:
  build-website:
    name: Build website
    # The deploy-website job already builds and deploys the website to GitHub pages on pushes to main,
    # no need to do it twice.
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

  deploy-website:
    name: Build and deploy website to GitHub Pages
    # Only run on pushes to main.
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Deploy website to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          full_commit_message: 'Deploy website for ${{ github.sha }}'
